version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - staticcheck
    - errcheck
    - govet
    - unused
    - ineffassign

  settings:
    staticcheck:
      checks: ["all"]

issues:
  exclude-use-default: false
