// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/quotes": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "quotes"
                ],
                "summary": "Get stored quote snapshots",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SwaggerQuotesResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/quotes/network": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "quotes"
                ],
                "summary": "Get a real-time network quote",
                "parameters": [
                    {
                        "description": "Network quote request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.SwaggerGetNetworkQuoteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.NetworkQuoteResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/quotes/pay-in": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "quotes"
                ],
                "summary": "Update pay-in quotes",
                "parameters": [
                    {
                        "description": "Pay-in quote groups",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.SwaggerUpdateQuotesRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.PublishResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/quotes/pay-out": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "quotes"
                ],
                "summary": "Update pay-out quotes",
                "parameters": [
                    {
                        "description": "Pay-out quote groups",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.SwaggerUpdateQuotesRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.PublishResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/quotes/publish": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "quotes"
                ],
                "summary": "Publish quotes to the network",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.PublishResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/quotes/publish/pay-in": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "quotes"
                ],
                "summary": "Publish quotes to the network",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.PublishResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/quotes/publish/pay-out": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "quotes"
                ],
                "summary": "Publish quotes to the network",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.PublishResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.APIDecimal": {
            "type": "object",
            "properties": {
                "exponent": {
                    "type": "integer"
                },
                "unscaled": {
                    "type": "integer"
                }
            }
        },
        "api.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "api.NetworkProviderQuote": {
            "type": "object",
            "properties": {
                "executable": {
                    "type": "boolean"
                },
                "expiration": {
                    "type": "string"
                },
                "payOutAmount": {
                    "$ref": "#/definitions/api.APIDecimal"
                },
                "quoteId": {
                    "$ref": "#/definitions/api.NetworkQuoteID"
                },
                "rate": {
                    "$ref": "#/definitions/api.APIDecimal"
                },
                "settlement": {
                    "$ref": "#/definitions/api.NetworkSettlement"
                }
            }
        },
        "api.NetworkQuoteFailure": {
            "type": "object",
            "properties": {
                "reason": {
                    "type": "string"
                }
            }
        },
        "api.NetworkQuoteID": {
            "type": "object",
            "properties": {
                "providerId": {
                    "type": "integer"
                },
                "quoteId": {
                    "type": "integer"
                }
            }
        },
        "api.NetworkQuoteResponse": {
            "type": "object",
            "properties": {
                "allQuotes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.NetworkProviderQuote"
                    }
                },
                "result": {
                    "$ref": "#/definitions/api.NetworkQuoteResult"
                }
            }
        },
        "api.NetworkQuoteResult": {
            "type": "object",
            "properties": {
                "failure": {
                    "$ref": "#/definitions/api.NetworkQuoteFailure"
                },
                "success": {
                    "$ref": "#/definitions/api.NetworkQuoteSuccess"
                }
            }
        },
        "api.NetworkQuoteSuccess": {
            "type": "object",
            "properties": {
                "expiration": {
                    "type": "string"
                },
                "payOutAmount": {
                    "$ref": "#/definitions/api.APIDecimal"
                },
                "quoteId": {
                    "$ref": "#/definitions/api.NetworkQuoteID"
                },
                "rate": {
                    "$ref": "#/definitions/api.APIDecimal"
                },
                "settlementAmount": {
                    "$ref": "#/definitions/api.APIDecimal"
                }
            }
        },
        "api.NetworkSettlement": {
            "type": "object",
            "properties": {
                "amount": {
                    "$ref": "#/definitions/api.APIDecimal"
                },
                "creditLimit": {
                    "$ref": "#/definitions/api.APIDecimal"
                },
                "prefundingAmount": {
                    "$ref": "#/definitions/api.APIDecimal"
                },
                "totalUsed": {
                    "$ref": "#/definitions/api.APIDecimal"
                }
            }
        },
        "api.PublishResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "published": {
                    "type": "boolean"
                }
            }
        },
        "api.SwaggerBand": {
            "type": "object",
            "properties": {
                "clientQuoteId": {
                    "type": "string"
                },
                "fix": {
                    "$ref": "#/definitions/api.APIDecimal"
                },
                "maxAmount": {
                    "$ref": "#/definitions/api.APIDecimal"
                },
                "rate": {
                    "$ref": "#/definitions/api.APIDecimal"
                }
            }
        },
        "api.SwaggerGetNetworkQuoteRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "$ref": "#/definitions/api.APIDecimal"
                },
                "amountType": {
                    "type": "string"
                },
                "payOutCurrency": {
                    "type": "string"
                },
                "payOutMethod": {
                    "type": "string"
                }
            }
        },
        "api.SwaggerQuoteGroup": {
            "type": "object",
            "properties": {
                "bands": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.SwaggerBand"
                    }
                },
                "currency": {
                    "type": "string"
                },
                "expiration": {
                    "type": "string"
                },
                "paymentMethod": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "api.SwaggerQuotesResponse": {
            "type": "object",
            "properties": {
                "payIn": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.SwaggerQuoteGroup"
                    }
                },
                "payOut": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.SwaggerQuoteGroup"
                    }
                }
            }
        },
        "api.SwaggerUpdateQuotesRequest": {
            "type": "object",
            "properties": {
                "groups": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.SwaggerQuoteGroup"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "api.agtpay.xyz",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "my-provider API",
	Description:      "Quote management REST API for the t-0 Network provider.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
